import logging

from github import Github

logger = logging.getLogger(__name__)

def create_pull_request(
        github_token: str, issue_id: str, repo_name: str, files: list, issue_description: str, sandbox_result: dict
    ) -> dict:
    """
    Create a PR with generated files.

    Args:
        github_token: GitHub personal access token
        issue_id: the ID of the Github issue, will be used as branch name
        repo_name: "owner/repo"
        files: [{"path": "...", "content": "..."}]
        workflow_id: Unique workflow ID
        issue_description: Original issue description
        sandbox_result: Results from sandbox testing

    Returns:
        {"pr_number": 123, "pr_url": "https://...", "current_step": "..."}
    """

    try:
        client = Github(github_token)
        repo = client.get_repo(repo_name)

        # 1. Get base branch SHA
        base_branch = repo.default_branch
        base_sha = repo.get_branch(base_branch).commit.sha

        # 2. Create new branch
        branch_name = f"autodev/{issue_id}"
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_sha
        )
        logger.info(f"Created branch: {branch_name}")

        # 3. Commit files to new branch
        for file in files:
            try:
                contents = repo.get_contents(file["path"], ref=branch_name)

                repo.update_file(
                    path=file["path"],
                    message=f"TraceGraph: Update {file["path"]}",
                    content=file["content"],
                    sha=contents.sha,
                    branch=branch_name
                )
                logger.info(f"Updated: {file['path']}")

            except:

                repo.create_file(
                    path=file["path"],
                    message=f"TraceGraph: Create {file['path']}",
                    content=file['content'],
                    branch=branch_name
                )

                logger.info(f"Created: {file['path']}")

                # 4. Create PR
        pr_body = f"""
                
        ## TraceGraph Generated PR

        **Original Query:** {issue_description}

        **Files Changed:** {len(files)}

        **Sandbox Tests:** {'Passed' if sandbox_result.get('success') else 'Failed'}

        **Test Duration:** {sandbox_result.get('duration_ms', 0) / 1000:.1f}s

        ---

        <details>
        <summary>Sandbox Logs</summary>
        ```
        {sandbox_result.get('logs', 'No logs available')[:2000]}
        ```
        </details>
        ---

        *Generated by TraceGraph workflow `{issue_id}`*
        """

        pr = repo.create_pull(
            title=f"[TraceGraph] {issue_description[:60]}",
            body=pr_body,
            head=branch_name,
            base=base_branch
        )


        logger.info(f"Created PR #{pr.number}: {pr.html_url}")

        return {
            "pr_number": pr.number,
            "pr_url": pr.html_url,
            "current_step": "completed"
        }            

    except Exception as e:

        logger.error(f"Failed to create PR: {e}", exc_info=True)
        raise